id: setup-wp

info:
  name: wp setup
  author: Soumen(Cyber_pent)
  severity: critical
  reference: https://twitter.com
  tags: rce,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}//wp-admin/setup-config.php?step=1"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Database Name"
        part: body

      - type: status
        status:
          - 200
